### PR TITLE
Add FOX222/FRX523 Guides

### PR DESCRIPTION
**Pull request by TeaRex-coder**
Hello! Based on the existing guides, the FAQ post in Discord and the FRX523 thread, I added the Frontier guide. I also added a README for the repo.

### CODE REVIEW

**Comment by djGrrr** [comment]
Nice work! There are just a few things that should be changed:
1. The comment on the MIB files should be removed (this is from the Bell Guide): VEIP and more 
2. The MIB File should also be marked mandatory, even though it is the default.
3. The latest known software version for the FRX523 as of last night is `R4.4.13.057`

**Comment by TeaRex-coder** [comment]
Thanks, I'll make those changes this afternoon.

**Comment by up-n-atom** [comment]
To keep your afternoon busy...

1. Frontier Communications Inc. https://en.wikipedia.org/wiki/Frontier_Communications (Dropping the Parent)
2. All attributes are mandatory for Frontier.
3. For Install Community... section: Copy/paste from the Bell Inc. guides rather than AT&T guide since the community firmware is required.
4. Mib File remark can be Default value

**Comment by TeaRex-coder** [comment]
There we go, it should be all good now! Thanks for your feedback.

**Pull request merged**
