### PR TITLE
Add URL for ECIN EN-XGSFPP-OMAC-V2

### PR DESCRIPTION
**Pull request by joeykrim**

### CODE REVIEW

**Comment by up-n-atom** [comment]
The reason I didn't add store links is because on the principle that we shouldn't be providing free sales and advertisements. Without an affiliate program or direct sponsorship why should we endure the costs?

We're fortunate to have generous individuals provide small donations here and there for the domain renewal, documentation, and direct support. We're open to cooperate but they've shut the door.

**Comment by joeykrim** [comment]
The principle is punishing the readers of the wiki.

The reader of this page will need to make a purchase.

Make lives easier for your users with a link and save them a Google search and revenue going to Google for ads.

Right now, ECIN and the others, just see(s) traffic from Google and not you, what incentive would their analytics give them to change their relationship with you?

Also, save your users from wondering if their search found the right thing and many users asking the same question over and over, is this the right one?

**Comment by miguemely** [comment]
I mean... they have been emailing everyone who has been ordering, and asking about use-case. That's enough incentive for a relationship.

**Comment by up-n-atom** [comment]
> The principle is punishing the readers of the wiki.
> 
> The reader of this page will need to make a purchase.
> 
> Make lives easier for your users with a link and save them a Google search and revenue going to Google for ads.
> 
> Right now, ECIN and the others, just see(s) traffic from Google and not you, what incentive would their analytics give them to change their relationship with you?
> 
> Also, save your users from wondering if their search found the right ONT, that they've likely never purchased before, and many users asking the same question over and over, is this the right one?

I'm going to relent and let the store links in but it's gotta be fair game. So please revise the pull for fibermall and I will add the half price listings from stores on Taobao and Alibaba.

**Comment by joeykrim** [comment]
https://github.com/up-n-atom/8311/pull/32

**Pull request closed without merging**
