### PR TITLE
add static route instructions for UDM Pro

### PR DESCRIPTION
**Pull request by Bjorn248**
# Context
I tried to follow this guide recently using my UDM pro but I struggled to follow the provided static IP instructions. I'm not sure why [4](https://pon.wiki/guides/install-8311-community-firmware-on-the-bfw-solutions-was-110/#fn:4) is linked at all, since the first IP in the subnet is 192.168.11.0, and the device has a static IP of 192.168.11.1. Did the author think that the `.1` address was the first address in the range? I got the feeling that there was some kind of confusion happening in the docs, but perhaps I'm the problem, it's certainly confusing for me! Why is that reference link at the beginning of the static IP section? 

I don't believe you need to set a static IP to be able to route to the WAS-110, all you need is a static route! I discovered that others also did this in the discord, which I joined after not being able to follow the docs successfully. 

I followed these steps with my UDM Pro with success, and I thought others might benefit from having these instructions.

# Changes
* add `site` to the gitignored files. This is the default output directory if you run `mkdocs build` locally to generate the site
* remove trailing whitespaces
* add a `Set a static route` section with instructions and screenshots for a UDM Pro
* ~removed the static IP instructions for Ubiquity - when I did this on my UDM Pro it did not work~

### CODE REVIEW

**Comment by up-n-atom** [comment]
> I tried to follow this guide recently using my UDM pro but I struggled to follow the provided static IP instructions. I'm not sure why [4](https://pon.wiki/guides/install-8311-community-firmware-on-the-bfw-solutions-was-110/#fn:4) is linked at all, since the first IP in the subnet is 192.168.11.0, and the device has a static IP of 192.168.11.1.

It remains from a prior revision where the guide explained to choose an IP within the `192.168.11.0/24` subnet, but unfortunately, predominantly Ubiquiti users didn't understand the concept of a subnet and kept using `192.168.11.0/24` as the IP rather than 1 to 254.

The entire section of the guide shouldn't even need to exist other than to explain that the default IP of the WAS-110 is 192.168.11.1 but we're in this mess because a vast majority have more money than knowledge.

#27 is open because there are a few ways and you're tackling 1 with this pull. SNAT was the common approach on Discord and was just repeated here.

We have had discussion on Discord about adding pfSense and OPNsense sections as well, but as I explained there, it has to be explicit, meaning you need to literally guide the user with either links or instructions on where to click.

So I will ask that this needs to be done for the UDM, as the follow up questions on Discord will be where is the static route section in the screenshots and we'll have no answers.

Ideally, the screenshots should also be of the full page UI, as it's easier to navigate for an novice, which unfortunately is the majority for Ubiquiti.

**Comment by Bjorn248** [comment]
> So I will ask that this needs to be done for the UDM, as the follow up questions on Discord will be where is the static route section in the screenshots and we'll have no answers.
> 

Unfortunately I don't have a pfSense/OPNSense install that I can use to create screenshots for that, otherwise I would! Does not having pfSense/OPNSense instructions in this PR prevent it from being merged?

> Ideally, the screenshots should also be of the full page UI, as it's easier to navigate for an novice, which unfortunately is the majority for Ubiquiti.

I can go ahead and take full page screenshots if that's preferable! I can also add some more explicit instructions just to help folks out a little more. 

Thanks for the quick reply!

**Comment by djGrrr** [comment]
Removing the state ip instructions does not make sense, as you cannot simply use a static route to reach the WAS-110, as soon as you have an issue with your internet and your DHCP ip is not there, the stick will be unreachable, as there is no ip address on the wan interfaces of the UDM, which is arguably the time when you need to access the stick the most.

**Comment by Bjorn248** [comment]
> Removing the static IP instructions does not make sense, as you cannot simply use a static route to reach the WAS-110; as soon as you have an issue with your internet and your DHCP IP is no longer there, the stick will be unreachable, as there is no ip address on the wan interfaces of the UDM, which is arguably the time when you need to access the stick the most.

I used this method to access the stick before I had configured it, so my WAN was effectively down during that time. I think all you need is a static route. I might be misunderstanding what you're suggesting though.

That being said, I'll go ahead and add them back as it sounds like folks are still getting value out of those instructions.

**Comment by up-n-atom** [comment]
> Unfortunately I don't have a pfSense/OPNSense install that I can use to create screenshots for that, otherwise I would! Does not having pfSense/OPNSense instructions in this PR prevent it from being merged?

Just using it as an example that hand holding needs to apply for these GUI based setups.

Yes, I would prefer if it is a full page screenshot. Ctrl + Shift + S in FireFox or Ctrl + Shift + P + type: "screenshot" in Chrome.

The entire section will likely need to be altered. I'm thinking something like

# Access WAS-110
* Static IP
* Static Route
* Source NAT
## Static IP
## Static Route
## Source NAT

SNAT apparently can be accomplished from the UI on the UDM. An issue still exists with the static IP because the UI is missing the ability to assign multiple IPs to an interface, so shit out of luck if it's a DHCP WAN.

**Comment by Bjorn248** [comment]
> Yes, I would prefer if it is a full page screenshot. Ctrl + Shift + S in FireFox or Ctrl + Shift + P + type: "screenshot" in Chrome.

Done!

> The entire section will likely need to be altered. I'm thinking something like
> # Access the WAS-110
> 
>     * Static IP (same subnet)
> 
>     * Static Route
> 
>     * Source NAT
> 
> 
> ## Static IP
> ## Static Route
> ## Source NAT
> 
> SNAT apparently can be accomplished from the UI on the UDM. An issue still exists with the static IP because the UI is missing the ability to assign multiple IPs to an interface, so shit out of luck if it's a DHCP WAN.

I renamed the new section to "Add a static route" but decided to leave out the SNAT section as I don't have any content to put there yet.

**Comment by Bjorn248** [comment]
Hey there @up-n-atom, just wondering if there's anything else I need to do? Any other changes you'd like me to make before this can be merged?

**Comment by up-n-atom** [comment]
Add static route instruction for UDM and the start of addressing #27

**Pull request merged**
